FROM python:3.10.7

WORKDIR /RandomWalk

# installing essential packages
RUN pip install networkx==2.8
RUN pip install numpy==1.24.3
RUN pip install scipy==1.10.1

RUN wget https://raw.githubusercontent.com/Reed-CompBio/random-walk-with-restart/ef6bd61e0c866c13205ae94c1301827817dc1abb/random_walk.py