FROM python:3.10.7

WORKDIR /RWR

# installing essential packages
RUN pip install networkx==2.8
RUN pip install numpy==1.24.3
RUN pip install scipy==1.10.1

RUN wget https://raw.githubusercontent.com/Reed-CompBio/random-walk-with-restart/ffc9a088ae02bb7cb984b84d2f98937298086ef1/random_walk.py