FROM python:3.10.7

WORKDIR /RWR

# installing essential packages
RUN pip install networkx==2.8 numpy==1.24.3 scipy==1.10.1

RUN wget https://raw.githubusercontent.com/Reed-CompBio/random-walk-with-restart/654dd5a63ae820a8ba962226c1c9a0f607d7f203/random_walk.py