#uses ubuntu as the base
FROM python:3.10.7

WORKDIR /MinCostFlow

RUN pip install ortools==9.4.1874

RUN wget https://raw.githubusercontent.com/gitter-lab/min-cost-flow/ea1added536d422b5ead7ba544af4e6fe0532210/minCostFlow.py
