FROM python:3.10.7

WORKDIR /RandomWalk

RUN pip install networkx==2.8
RUN pip install numpy==1.24.3

RUN wget https://raw.githubusercontent.com/Lyce24/random-walk-with-restart/6b3842b5031fd30ee8106b804024c4160af2d0b5/random_walk.py