FROM python:3.10.7

WORKDIR /RandomWalk

RUN pip install networkx==2.8
RUN pip install numpy==1.24.3
RUN pip install scipy==1.10.1

RUN wget https://raw.githubusercontent.com/Lyce24/random-walk-with-restart/3da4d3c4f88e724ea7067074619c3843904edb0c/random_walk.py