FROM python:3.10.7

WORKDIR /RandomWalk

RUN pip install networkx==2.8
RUN pip install numpy==1.24.3
RUN pip install scipy==1.10.1

RUN wget https://raw.githubusercontent.com/Lyce24/random-walk-with-restart/a84761526fd97f9241a02723ca16480a1027c848/random_walk.py