#uses ubuntu as the base
FROM python:3.10.7

WORKDIR /ResponseNet

RUN pip install ortools && pip install networkx

# Last built 7/26/24 @ 2:45 PM PST
RUN wget https://raw.githubusercontent.com/Reed-CompBio/ResponseNet/40f3ff9b0db1391b0709c49cc7140dced0ed9102/responsenet.py

