FROM mcr.microsoft.com/devcontainers/base:1-bookworm

# Install dependencies necessary to build Singularity
RUN sudo apt-get update && sudo apt-get install -y \
    autoconf \
    automake \
    cryptsetup \
    fuse2fs \
    git \
    fuse \
    libfuse-dev \
    libseccomp-dev \
    libtool \
    pkg-config \
    runc \
    squashfs-tools \
    squashfs-tools-ng \
    uidmap \
    wget \
    zlib1g-dev
