hash_length: 7
containers:
  framework: docker
  unpack_singularity: false
  registry:
    base_url: docker.io
    owner: reedcompbio

# Each algorithm has an 'include' parameter. By toggling 'include' to true/false the user can change
# which algorithms are run in a given experiment.
#
# algorithm-specific parameters are embedded in lists so that users can specify multiple. If multiple
# parameters are specified then the algorithm will be run as many times as needed to cover all parameter
# combinations. For instance if we have the following:
# - name: "myAlg"
#   params:
#         include: true
#         a: [1,2]
#         b: [0.5,0.75]
#
# then myAlg will be run on (a=1,b=0.5),(a=1,b=0.75),(a=2,b=0.5), and (a=2,b=0,75). Pretty neat, but be
# careful: too many parameters might make your runs take a long time.

# TODO: get rid of the algorithms that will take too long to run
algorithms:
  - name: "pathlinker"
    include: true
    runs:
      run1:
        k: [1, 10, 100, 1000]

  - name: omicsintegrator2
    include: true
    runs:
      run1:
        b: [4, 10]
        g: [0, 3]
        w: [0.25, 6]

  - name: mincostflow
    include: true
    runs:
      run1:
        capacity: [15, 30]
        flow: [80, 15]

  - name: "strwr"
    include: true
    runs:
      run1:
        alpha: 0.85
        threshold: [100, 200]

  - name: "rwr"
    include: true
    runs:
      run1:
        alpha: 0.85
        threshold: [100, 200]

# Here we specify which pathways to run and other file location information.
# Assume that if a dataset label does not change, the lists of associated input files do not change
datasets:
  - # Labels can only contain letters, numbers, or underscores
    label: egfr
    node_files: ["tps-egfr-prizes.txt"] # the input nodes
    edge_files: ["phosphosite-irefindex13.0-uniprot.txt"] # the interactome
    # Placeholder
    other_files: []
    # Relative path from the spras directory where these files live
    data_dir: "input"

gold_standards:
  - # Labels can only contain letters, numbers, or underscores
    label: gs_egfr
    node_files: ["gs-egfr.txt"]
    data_dir: "input"
    # List of dataset labels to compare with the specific gold standard dataset
    dataset_labels: ["egfr"]

reconstruction_settings:

  # Set where everything is saved
  locations:
    reconstruction_dir: "output/intermediate"

analysis:
  summary:
    include: true # set to true for step 4

  # Machine learning analysis (e.g. clustering) of the pathway output files for each dataset
  ml:
    # ml analysis per dataset
    include: true # set to true for step 3

    # set all below to true for step 4??
    # adds ml analysis per algorithm output
    # only runs for algorithms with multiple parameter combinations chosen
    aggregate_per_algorithm: true # set to true for step 4
    # overalls a kernel density estimation over pca
    kde: true # set to true for step 4
    # removes empty pathways from consideration in ml analysis (pca only)
    remove_empty_pathways: true # set to true for step 4

  evaluation:
    # evaluation per dataset-goldstandard pair
    # evaluation will not run unless ml include is set to true
    include: true # set to true for step 4
    # adds evaluation per algorithm per dataset-goldstandard pair
    # evaluation per algorithm will not run unless ml include and ml aggregate_per_algorithm are set to true
    aggregate_per_algorithm: true # set to true for step 4
