# Create a Docker image for the Local Neighborhood algorithm here
FROM python:3.10.10-alpine

# tell Docker what to build
WORKDIR /LocalNeighborhood

# copy the local neighborhood algorithm into the container
COPY local_neighborhood.py .