FROM openjdk:8

WORKDIR /MuST
RUN export MUST_SHA=7453efcd8fc2d3b3e51b3724d44afdd1f7a947a3 && \
    wget https://github.com/repotrial/MultiSteinerBackend/raw/$MUST_SHA/out/artifacts/MultiSteinerBackend_jar/MultiSteinerBackend.jar
