name: Build SPRAS Containers

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - master

jobs:
  build-and-remove-omics1:
    uses: "./.github/workflows/build-and-remove-template.yml"
    with:
      path: docker-wrappers/OmicsIntegrator1
      container: ghcr.io/reed-compbio/omics-integrator-1
  build-and-remove-omics2:
    uses: "./.github/workflows/build-and-remove-template.yml"
    with:
      path: docker-wrappers/OmicsIntegrator2
      container: ghcr.io/reed-compbio/omics-integrator-2
  build-and-remove-pathlinker:
    uses: "./.github/workflows/build-and-remove-template.yml"
    with:
      path: docker-wrappers/PathLinker
      container: ghcr.io/reed-compbio/pathlinker
  build-and-remove-meo:
    uses: "./.github/workflows/build-and-remove-template.yml"
    with:
      path: docker-wrappers/MEO
      container: ghcr.io/reed-compbio/meo
  build-and-remove-mincostflow:
    uses: "./.github/workflows/build-and-remove-template.yml"
    with:
      path: docker-wrappers/MinCostFlow
      container: ghcr.io/reed-compbio/mincostflow
  build-and-remove-allpairs:
    uses: "./.github/workflows/build-and-remove-template.yml"
    with:
      path: docker-wrappers/AllPairs
      container: ghcr.io/reed-compbio/allpairs
  build-and-remove-domino:
    uses: "./.github/workflows/build-and-remove-template.yml"
    with:
      path: docker-wrappers/DOMINO
      container: ghcr.io/reed-compbio/domino
  build-and-remove-btb:
    uses: "./.github/workflows/build-and-remove-template.yml"
    with:
      path: docker-wrappers/BowTieBuilder
      container: ghcr.io/reed-compbio/bowtiebuilder
  build-and-remove-cytoscape:
    uses: "./.github/workflows/build-and-remove-template.yml"
    with:
      path: docker-wrappers/Cytoscape
      container: ghcr.io/reed-compbio/py4cytoscape
  build-and-remove-responsenet:
    uses: "./.github/workflows/build-and-remove-template.yml"
    with:
      path: docker-wrappers/ResponseNet
      container: reed-compbio/responsenet
  build-and-remove-spras:
    uses: "./.github/workflows/build-and-remove-template.yml"
    with:
      path: docker-wrappers/SPRAS
      container: ghcr.io/reed-compbio/spras
      # Since any change to the SPRAS codebase would constitute a change to
      # the container we produce in this step, build the container regardless
      # of detected changes.
      always_build: true
      context: ./
