name: Push to Docker

on:
  workflow_dispatch:
    inputs:
      folder:
        description: 'The folder to push'
        required: true
        type: string
      version:
        description: 'The version to use (e.g. v1)'
        required: true
        type: string

jobs:
  push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Run build.py
        run: python3 docker-wrappers/build.py --dir ${{ inputs.folder }} --version ${{ inputs.version }} --yes
